In [1]:
# Goal: Use the DeFiLlama API to pull data on multiple tokens and use the TVL available via defillama (for free and without a key!) to create some exceptional interactive data visualizations with plotly.express (px)

In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px

import requests
import urllib3
import json
import datetime as dt
import urllib
import urllib.parse
import time

from datetime import datetime, timedelta
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
from requests.packages.urllib3.exceptions import InsecureRequestWarning

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

import warnings
warnings.simplefilter('ignore')

In [2]:
# DFL Library import & API init:
from defillama import DefiLlama

llama = DefiLlama()

In [6]:
# help menu on 'llama' will show all of the built-in methods available via the dfl wrapper:
help(llama)

Help on DefiLlama in module defillama.defillama object:

class DefiLlama(builtins.object)
 |  DeFi Llama class to act as DeFi Llama's API client.
 |  All the requests can be made through this class.
 |
 |  Methods defined here:
 |
 |  __init__(self)
 |      Initialize the object
 |
 |  get_all_protocols(self)
 |      Returns basic information on all listed protocols, their current
 |      TVL and the changes to it in the last hour/day/week.
 |      Endpoint: GET /protocols
 |
 |      :return: JSON response
 |
 |  get_batch_historical_prices(self, coins: str, searchWidth: str = '600')
 |      Get historical prices of tokens by contract address
 |
 |  get_chain_dexs(self, chain, excludeTotalDataChart=True, excludeTotalDataChartBreakdown=True, dataType='dailyVolume')
 |      list all dexs filter by chain
 |
 |  get_chain_options_dexs(self, chain, excludeTotalDataChart=True, excludeTotalDataChartBreakdown=True, dataType='dailyVolume')
 |      list all options dexs
 |
 |  get_chains_current_tvl(self)
 |      Returns list of current TVL of all chains.
 |
 |      :return: JSON response
 |
 |  get_closest_ts_block(self, chain: str, timestamp: int)
 |      Get the closest block to a timestamp
 |
 |  get_dex_summary(self, protocol, excludeTotalDataChart=True, excludeTotalDataChartBreakdown=True, dataType='dailyVolume')
 |      get summary of dex volume with historical data
 |
 |  get_dexs(self, excludeTotalDataChart=True, excludeTotalDataChartBreakdown=True, dataType='dailyVolume')
 |      list all dexs
 |
 |  get_earliest_ts_price(self, coins: str)
 |      Get earliest timestamp price record for coins
 |
 |  get_fees(self, excludeTotalDataChart=True, excludeTotalDataChartBreakdown=True, dataType='dailyFees')
 |      list all protocols along with summaries of their fees & revenue & dataType history data
 |
 |  get_fees_chain(self, chain, excludeTotalDataChart=True, excludeTotalDataChartBreakdown=True, dataType='dailyFees')
 |      list all protocols along with summaries of their fees & revenue & dataType history data by chain
 |
 |  get_fees_protocol(self, protocol, dataType='dailyFees')
 |      Get summary of protocol fees and revenue with historical data
 |
 |  get_historical_tvl(self)
 |      Get Historical TVL of DeFi on all chains
 |
 |      :return: JSON response
 |
 |  get_historical_tvl_chain(self, chain)
 |      Get Historical TVL of a chain
 |
 |      :return: JSON response
 |
 |  get_options_dex_summary(self, protocol, dataType='dailyPremiumVolume')
 |      get summary of option dex volume with historical data
 |
 |  get_options_dexs(self, excludeTotalDataChart=True, excludeTotalDataChartBreakdown=True, dataType='dailyVolume')
 |      list all options dexs
 |
 |  get_percentage_price_change(self, coins: str, timestamp: int, lookForward: bool = False, period: str = '3w')
 |      Get percentage change in price over time
 |
 |  get_pool(self, pool: str)
 |      Get the historical APY & TVL data for a pool
 |
 |  get_pools(self)
 |      Get the latest data for all pools
 |
 |  get_protocol(self, name)
 |      Returns historical data on the TVL of a protocol along with some basic data on it.
 |      The fields `tokensInUsd` and `tokens` are only available for some protocols..
 |      Endpoint: GET /protocol/{name}
 |
 |      :param: name : ID of the protocol to get (eg: uniswap, WBTC...).
 |          This can be obtained from the /protocols endpoint
 |      :return: JSON response
 |
 |  get_protocol_current_tvl(self, protocol)
 |      Simplified endpoint that only returns a number, the current TVL of a protocol
 |
 |      :param: name : ID of the protocol to get (eg: uniswap, WBTC...).
 |          This can be obtained from the /protocols endpoint
 |      :return: JSON response
 |
 |  get_stablecoins(self, include_prices: bool = True)
 |      List all stablecoins along with their circulating amounts
 |
 |  get_stablecoins_all_current_mcap_sum(self)
 |      Get current mcap sum of all stablecoins on each chain
 |
 |  get_stablecoins_all_historical_mcap_sum(self, stablecoin_id: int)
 |      Get historical mcap sum of all stablecoins
 |
 |  get_stablecoins_chains_all_historical_mcap_sum(self, chain: str, stablecoin_id: int)
 |      Get historical mcap sum of all stablecoins in a chain
 |
 |  get_stablecoins_historical_mcap_n_chain_distribution(self, stablecoin_id: int)
 |      Get historical mcap & historical chain distribution of a stablecoin
 |
 |  get_stablecoins_historical_prices(self)
 |      Get historical prices of all stablecoins
 |
 |  get_token_current_prices(self, coins: str, searchWidth: str = '4h')
 |      Get current prices of tokens by contract address
 |
 |  get_token_historical_prices(self, coins: str, timestamp: int, searchWidth: str = '4h')
 |      Get historical prices of tokens by contract address
 |
 |  get_token_prices_at_intervals(self, coins: str, start: int, end: int, span: int = 0, period: str = '2d', searchWidth: str = '600')
 |      Get token prices at regular time intervals
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [3]:
# Pull all historical data for Solana (entire chain); this will be used in our viz as a benchmark;

solana_data = llama.get_historical_tvl_chain('Solana')
solana_data

[{'date': 1616025600, 'tvl': 148988798},
 {'date': 1616112000, 'tvl': 153204289},
 {'date': 1616198400, 'tvl': 147690914},
 {'date': 1616284800, 'tvl': 151935325},
 {'date': 1616371200, 'tvl': 152981122},
 {'date': 1616457600, 'tvl': 162065403},
 {'date': 1616544000, 'tvl': 156101311},
 {'date': 1616630400, 'tvl': 144439504},
 {'date': 1616716800, 'tvl': 135610450},
 {'date': 1616803200, 'tvl': 147786656},
 {'date': 1616889600, 'tvl': 172583244},
 {'date': 1616976000, 'tvl': 189014228},
 {'date': 1617062400, 'tvl': 202157669},
 {'date': 1617148800, 'tvl': 209794033},
 {'date': 1617235200, 'tvl': 216074736},
 {'date': 1617321600, 'tvl': 236083655},
 {'date': 1617408000, 'tvl': 236307232},
 {'date': 1617494400, 'tvl': 236512420},
 {'date': 1617580800, 'tvl': 236284645},
 {'date': 1617667200, 'tvl': 272660066},
 {'date': 1617753600, 'tvl': 268791821},
 {'date': 1617840000, 'tvl': 279546575},
 {'date': 1617926400, 'tvl': 294784827},
 {'date': 1618012800, 'tvl': 331055199},
 {'date': 1618099200, 'tvl': 647826457},
 {'date': 1618185600, 'tvl': 739114210},
 {'date': 1618272000, 'tvl': 725197241},
 {'date': 1618358400, 'tvl': 789380856},
 {'date': 1618444800, 'tvl': 845183863},
 {'date': 1618531200, 'tvl': 832431640},
 {'date': 1618617600, 'tvl': 824389987},
 {'date': 1618704000, 'tvl': 731812653},
 {'date': 1618790400, 'tvl': 752985413},
 {'date': 1618876800, 'tvl': 679436372},
 {'date': 1618963200, 'tvl': 829344535},
 {'date': 1619049600, 'tvl': 856891182},
 {'date': 1619136000, 'tvl': 944231588},
 {'date': 1619222400, 'tvl': 901200587},
 {'date': 1619308800, 'tvl': 916208113},
 {'date': 1619395200, 'tvl': 1069894340},
 {'date': 1619481600, 'tvl': 1276677940},
 {'date': 1619568000, 'tvl': 1329654493},
 {'date': 1619654400, 'tvl': 1323930069},
 {'date': 1619740800, 'tvl': 1251700240},
 {'date': 1619827200, 'tvl': 1355254181},
 {'date': 1619913600, 'tvl': 1470780217},
 {'date': 1620000000, 'tvl': 1540847058},
 {'date': 1620086400, 'tvl': 1556253722},
 {'date': 1620172800, 'tvl': 1508702507},
 {'date': 1620259200, 'tvl': 1539822922},
 {'date': 1620345600, 'tvl': 1537938603},
 {'date': 1620432000, 'tvl': 1548041003},
 {'date': 1620518400, 'tvl': 1599948716},
 {'date': 1620604800, 'tvl': 1622269712},
 {'date': 1620691200, 'tvl': 1571029533},
 {'date': 1620777600, 'tvl': 1633176756},
 {'date': 1620864000, 'tvl': 1435048916},
 {'date': 1620950400, 'tvl': 1496478540},
 {'date': 1621036800, 'tvl': 1382212605},
 {'date': 1621123200, 'tvl': 1549574579},
 {'date': 1621209600, 'tvl': 1125804868},
 {'date': 1621296000, 'tvl': 1296947874},
 {'date': 1621382400, 'tvl': 875150588},
 {'date': 1621468800, 'tvl': 973602542},
 {'date': 1621555200, 'tvl': 715568965},
 {'date': 1621641600, 'tvl': 790006618},
 {'date': 1621728000, 'tvl': 658552593},
 {'date': 1621814400, 'tvl': 768757432},
 {'date': 1621900800, 'tvl': 612657114},
 {'date': 1621987200, 'tvl': 857310002},
 {'date': 1622073600, 'tvl': 850953177},
 {'date': 1622160000, 'tvl': 791685442},
 {'date': 1622246400, 'tvl': 736826756},
 {'date': 1622332800, 'tvl': 813407821},
 {'date': 1622419200, 'tvl': 880378004},
 {'date': 1622505600, 'tvl': 670808190},
 {'date': 1622592000, 'tvl': 848207713},
 {'date': 1622678400, 'tvl': 760054301},
 {'date': 1622764800, 'tvl': 740082595},
 {'date': 1622851200, 'tvl': 725056470},
 {'date': 1622937600, 'tvl': 742389346},
 {'date': 1623024000, 'tvl': 735811188},
 {'date': 1623110400, 'tvl': 691338751},
 {'date': 1623196800, 'tvl': 689235758},
 {'date': 1623283200, 'tvl': 638617904},
 {'date': 1623369600, 'tvl': 556162146},
 {'date': 1623456000, 'tvl': 534624148},
 {'date': 1623542400, 'tvl': 541039253},
 {'date': 1623628800, 'tvl': 556519807},
 {'date': 1623715200, 'tvl': 584211544},
 {'date': 1623801600, 'tvl': 547748099},
 {'date': 1623888000, 'tvl': 540478965},
 {'date': 1623974400, 'tvl': 516185477},
 {'date': 1624060800, 'tvl': 502604659},
 {'date': 1624147200, 'tvl': 506128155},
 {'date': 1624233600, 'tvl': 466164686},
 {'date': 1624320000, 'tvl': 447502806},
 {'date': 1624406400, 'tvl': 444512249},
 {'date': 1624492800, 'tvl': 448430968},
 {'date': 1624579200, 'tvl': 451721654},
 {'date': 1624665600, 'tvl': 423082407},
 {'date': 1624752000, 'tvl': 449526718},
 {'date': 1624838400, 'tvl': 463489716},
 {'date': 1624924800, 'tvl': 479139300},
 {'date': 1625011200, 'tvl': 491278563},
 {'date': 1625097600, 'tvl': 507472546},
 {'date': 1625184000, 'tvl': 790560134},
 {'date': 1625270400, 'tvl': 869787883},
 {'date': 1625356800, 'tvl': 873447775},
 {'date': 1625443200, 'tvl': 853035678},
 {'date': 1625529600, 'tvl': 885504288},
 {'date': 1625616000, 'tvl': 898078492},
 {'date': 1625702400, 'tvl': 855072856},
 {'date': 1625788800, 'tvl': 858662277},
 {'date': 1625875200, 'tvl': 848788419},
 {'date': 1625961600, 'tvl': 855127871},
 {'date': 1626048000, 'tvl': 832663878},
 {'date': 1626134400, 'tvl': 822681126},
 {'date': 1626220800, 'tvl': 831885719},
 {'date': 1626307200, 'tvl': 785680901},
 {'date': 1626393600, 'tvl': 781718509},
 {'date': 1626480000, 'tvl': 876082630},
 {'date': 1626566400, 'tvl': 886311874},
 {'date': 1626652800, 'tvl': 861778925},
 {'date': 1626739200, 'tvl': 854373926},
 {'date': 1626825600, 'tvl': 891610557},
 {'date': 1626912000, 'tvl': 919195017},
 {'date': 1626998400, 'tvl': 949581083},
 {'date': 1627084800, 'tvl': 970500585},
 {'date': 1627171200, 'tvl': 986521609},
 {'date': 1627257600, 'tvl': 997549981},
 {'date': 1627344000, 'tvl': 1023543513},
 {'date': 1627430400, 'tvl': 1066854851},
 {'date': 1627516800, 'tvl': 1135937952},
 {'date': 1627603200, 'tvl': 1192566473},
 {'date': 1627689600, 'tvl': 1244169934},
 {'date': 1627776000, 'tvl': 1204468607},
 {'date': 1627862400, 'tvl': 1235666585},
 {'date': 1627948800, 'tvl': 1245829134},
 {'date': 1628035200, 'tvl': 1290175469},
 {'date': 1628121600, 'tvl': 1364332725},
 {'date': 1628208000, 'tvl': 1314146303},
 {'date': 1628294400, 'tvl': 1327362329},
 {'date': 1628380800, 'tvl': 1304155428},
 {'date': 1628467200, 'tvl': 1361913466},
 {'date': 1628553600, 'tvl': 1343991879},
 {'date': 1628640000, 'tvl': 1343511250},
 {'date': 1628726400, 'tvl': 1402560821},
 {'date': 1628812800, 'tvl': 1463369152},
 {'date': 1628899200, 'tvl': 1508051128},
 {'date': 1628985600, 'tvl': 1631699574},
 {'date': 1629072000, 'tvl': 1729658494},
 {'date': 1629158400, 'tvl': 1786087699},
 {'date': 1629244800, 'tvl': 1997161281},
 {'date': 1629331200, 'tvl': 2103736573},
 {'date': 1629417600, 'tvl': 2274158627},
 {'date': 1629504000, 'tvl': 2275112735},
 {'date': 1629590400, 'tvl': 2218000709},
 {'date': 1629676800, 'tvl': 2250117206},
 {'date': 1629763200, 'tvl': 2204595033},
 {'date': 1629849600, 'tvl': 2193191447},
 {'date': 1629936000, 'tvl': 2253275462},
 {'date': 1630022400, 'tvl': 2439598288},
 {'date': 1630108800, 'tvl': 2567798841},
 {'date': 1630195200, 'tvl': 2593429466},
 {'date': 1630281600, 'tvl': 2709652837},
 {'date': 1630368000, 'tvl': 2735864216},
 {'date': 1630454400, 'tvl': 2877963189},
 {'date': 1630540800, 'tvl': 3029584099},
 {'date': 1630627200, 'tvl': 3191574878},
 {'date': 1630713600, 'tvl': 3328505721},
 {'date': 1630800000, 'tvl': 3546418518},
 {'date': 1630886400, 'tvl': 4208649902},
 {'date': 1630972800, 'tvl': 3966327656},
 {'date': 1631059200, 'tvl': 4816807931},
 {'date': 1631145600, 'tvl': 5658526091},
 {'date': 1631232000, 'tvl': 6350729997},
 {'date': 1631318400, 'tvl': 6694664395},
 {'date': 1631404800, 'tvl': 7604633492},
 {'date': 1631491200, 'tvl': 7326415290},
 {'date': 1631577600, 'tvl': 7151040149},
 {'date': 1631664000, 'tvl': 7131258837},
 {'date': 1631750400, 'tvl': 6704300350},
 {'date': 1631836800, 'tvl': 6483722696},
 {'date': 1631923200, 'tvl': 7201356137},
 {'date': 1632009600, 'tvl': 6882391944},
 {'date': 1632096000, 'tvl': 5953651385},
 {'date': 1632182400, 'tvl': 5543049946},
 {'date': 1632268800, 'tvl': 6276025425},
 {'date': 1632355200, 'tvl': 6556372861},
 {'date': 1632441600, 'tvl': 6268148421},
 {'date': 1632528000, 'tvl': 6353408537},
 {'date': 1632614400, 'tvl': 6342540190},
 {'date': 1632700800, 'tvl': 6323728768},
 {'date': 1632787200, 'tvl': 6147041840},
 {'date': 1632873600, 'tvl': 6277367087},
 {'date': 1632960000, 'tvl': 6617236505},
 {'date': 1633046400, 'tvl': 7114242817},
 {'date': 1633132800, 'tvl': 7220803330},
 {'date': 1633219200, 'tvl': 7441217915},
 {'date': 1633305600, 'tvl': 7300749820},
 {'date': 1633392000, 'tvl': 7270422667},
 {'date': 1633478400, 'tvl': 6900156538},
 {'date': 1633564800, 'tvl': 6649879818},
 {'date': 1633651200, 'tvl': 6650989615},
 {'date': 1633737600, 'tvl': 6668108737},
 {'date': 1633824000, 'tvl': 6535290908},
 {'date': 1633910400, 'tvl': 6552348938},
 {'date': 1633996800, 'tvl': 6623123168},
 {'date': 1634083200, 'tvl': 7787820635},
 {'date': 1634169600, 'tvl': 7865264964},
 {'date': 1634256000, 'tvl': 7534917475},
 {'date': 1634342400, 'tvl': 7621040592},
 {'date': 1634428800, 'tvl': 7925872554},
 {'date': 1634515200, 'tvl': 7640107857},
 {'date': 1634601600, 'tvl': 7461956613},
 {'date': 1634688000, 'tvl': 7466363059},
 {'date': 1634774400, 'tvl': 7933436821},
 {'date': 1634860800, 'tvl': 7868042413},
 {'date': 1634947200, 'tvl': 7707026730},
 {'date': 1635033600, 'tvl': 8115070507},
 {'date': 1635120000, 'tvl': 8183788321},
 {'date': 1635206400, 'tvl': 8449789045},
 {'date': 1635292800, 'tvl': 8219139877},
 {'date': 1635379200, 'tvl': 7726205440},
 {'date': 1635465600, 'tvl': 8027081125},
 {'date': 1635552000, 'tvl': 7920353255},
 {'date': 1635638400, 'tvl': 7853513235},
 {'date': 1635724800, 'tvl': 8115703748},
 {'date': 1635811200, 'tvl': 8115212180},
 {'date': 1635897600, 'tvl': 8526959834},
 {'date': 1635984000, 'tvl': 9794133173},
 {'date': 1636070400, 'tvl': 9804364557},
 {'date': 1636156800, 'tvl': 9659963037},
 {'date': 1636243200, 'tvl': 9961743713},
 {'date': 1636329600, 'tvl': 9933530531},
 {'date': 1636416000, 'tvl': 10027276058},
 {'date': 1636502400, 'tvl': 9708705937},
 {'date': 1636588800, 'tvl': 9305929286},
 {'date': 1636675200, 'tvl': 9610132340},
 {'date': 1636761600, 'tvl': 9509495458},
 {'date': 1636848000, 'tvl': 9676660601},
 {'date': 1636934400, 'tvl': 9597029012},
 {'date': 1637020800, 'tvl': 9400644816},
 {'date': 1637107200, 'tvl': 8934429975},
 {'date': 1637193600, 'tvl': 8963456377},
 {'date': 1637280000, 'tvl': 8284863411},
 {'date': 1637366400, 'tvl': 8734078017},
 {'date': 1637452800, 'tvl': 8721983483},
 {'date': 1637539200, 'tvl': 8701078197},
 {'date': 1637625600, 'tvl': 8333533673},
 {'date': 1637712000, 'tvl': 8436786678},
 {'date': 1637798400, 'tvl': 8548154789},
 {'date': 1637884800, 'tvl': 8558940009},
 {'date': 1637971200, 'tvl': 7975727436},
 {'date': 1638057600, 'tvl': 7977267278},
 {'date': 1638144000, 'tvl': 8213629197},
 {'date': 1638230400, 'tvl': 8423492804},
 {'date': 1638316800, 'tvl': 8477726900},
 {'date': 1638403200, 'tvl': 8690625487},
 {'date': 1638489600, 'tvl': 8573321674},
 {'date': 1638576000, 'tvl': 8217718286},
 {'date': 1638662400, 'tvl': 7228674575},
 {'date': 1638748800, 'tvl': 7090293935},
 {'date': 1638835200, 'tvl': 7090818319},
 {'date': 1638921600, 'tvl': 7024538846},
 {'date': 1639008000, 'tvl': 7232216943},
 {'date': 1639094400, 'tvl': 6951538211},
 {'date': 1639180800, 'tvl': 6358872890},
 {'date': 1639267200, 'tvl': 6478340403},
 {'date': 1639353600, 'tvl': 6562382733},
 {'date': 1639440000, 'tvl': 6368195884},
 {'date': 1639526400, 'tvl': 6448505134},
 {'date': 1639612800, 'tvl': 6774841742},
 {'date': 1639699200, 'tvl': 6736445335},
 {'date': 1639785600, 'tvl': 6598505688},
 {'date': 1639872000, 'tvl': 6914154542},
 {'date': 1639958400, 'tvl': 6833148072},
 {'date': 1640044800, 'tvl': 6626928722},
 {'date': 1640131200, 'tvl': 6822615143},
 {'date': 1640217600, 'tvl': 6777634406},
 {'date': 1640304000, 'tvl': 7089737850},
 {'date': 1640390400, 'tvl': 7064679087},
 {'date': 1640476800, 'tvl': 7023307330},
 {'date': 1640563200, 'tvl': 7140271136},
 {'date': 1640649600, 'tvl': 7050882480},
 {'date': 1640736000, 'tvl': 6732377650},
 {'date': 1640822400, 'tvl': 6561190253},
 {'date': 1640908800, 'tvl': 6432190593},
 {'date': 1640995200, 'tvl': 6559829856},
 {'date': 1641081600, 'tvl': 6700501937},
 {'date': 1641168000, 'tvl': 6704021952},
 {'date': 1641254400, 'tvl': 6517690974},
 {'date': 1641340800, 'tvl': 6593987447},
 {'date': 1641427200, 'tvl': 6238078126},
 {'date': 1641513600, 'tvl': 6002713804},
 {'date': 1641600000, 'tvl': 5518693723},
 {'date': 1641686400, 'tvl': 5382213690},
 {'date': 1641772800, 'tvl': 5476959880},
 {'date': 1641859200, 'tvl': 5223230801},
 {'date': 1641945600, 'tvl': 5341695413},
 {'date': 1642032000, 'tvl': 5472717669},
 {'date': 1642118400, 'tvl': 5311961489},
 {'date': 1642204800, 'tvl': 5392655938},
 {'date': 1642291200, 'tvl': 5518692262},
 {'date': 1642377600, 'tvl': 5559393537},
 {'date': 1642464000, 'tvl': 5491635457},
 {'date': 1642550400, 'tvl': 5487748614},
 {'date': 1642636800, 'tvl': 5613992223},
 {'date': 1642723200, 'tvl': 5399515576},
 {'date': 1642809600, 'tvl': 4843182721},
 {'date': 1642896000, 'tvl': 4514168198},
 {'date': 1642982400, 'tvl': 4466301676},
 {'date': 1643068800, 'tvl': 4376219740},
 {'date': 1643155200, 'tvl': 4467853090},
 {'date': 1643241600, 'tvl': 4485182525},
 {'date': 1643328000, 'tvl': 4429324066},
 {'date': 1643414400, 'tvl': 4590744235},
 {'date': 1643500800, 'tvl': 4730291107},
 {'date': 1643587200, 'tvl': 4600023965},
 {'date': 1643673600, 'tvl': 4751626794},
 {'date': 1643760000, 'tvl': 4929584825},
 {'date': 1643846400, 'tvl': 4223013963},
 {'date': 1643932800, 'tvl': 4410536014},
 {'date': 1644019200, 'tvl': 4785167923},
 {'date': 1644105600, 'tvl': 4875181830},
 {'date': 1644192000, 'tvl': 4840454317},
 {'date': 1644278400, 'tvl': 4915969584},
 {'date': 1644364800, 'tvl': 4860926395},
 {'date': 1644451200, 'tvl': 5090786283},
 {'date': 1644537600, 'tvl': 4895276509},
 {'date': 1644624000, 'tvl': 4686624486},
 {'date': 1644710400, 'tvl': 4623671635},
 {'date': 1644796800, 'tvl': 4587772050},
 {'date': 1644883200, 'tvl': 4634247200},
 {'date': 1644969600, 'tvl': 4777078817},
 {'date': 1645056000, 'tvl': 4706100610},
 {'date': 1645142400, 'tvl': 4573603903},
 {'date': 1645228800, 'tvl': 4494109740},
 {'date': 1645315200, 'tvl': 4441454304},
 {'date': 1645401600, 'tvl': 4452219037},
 {'date': 1645488000, 'tvl': 4327820079},
 {'date': 1645574400, 'tvl': 4319769339},
 {'date': 1645660800, 'tvl': 4170613845},
 {'date': 1645747200, 'tvl': 4254827322},
 {'date': 1645833600, 'tvl': 4295698123},
 {'date': 1645920000, 'tvl': 4272832360},
 {'date': 1646006400, 'tvl': 4085776340},
 {'date': 1646092800, 'tvl': 4409302548},
 {'date': 1646179200, 'tvl': 4358228042},
 {'date': 1646265600, 'tvl': 4297796873},
 {'date': 1646352000, 'tvl': 4184239542},
 {'date': 1646438400, 'tvl': 4085354776},
 {'date': 1646524800, 'tvl': 4054125002},
 {'date': 1646611200, 'tvl': 4052971283},
 {'date': 1646697600, 'tvl': 3965703556},
 {'date': 1646784000, 'tvl': 3928900001},
 {'date': 1646870400, 'tvl': 4137838843},
 {'date': 1646956800, 'tvl': 3951124719},
 {'date': 1647043200, 'tvl': 4155248962},
 {'date': 1647129600, 'tvl': 4249152047},
 {'date': 1647216000, 'tvl': 3989486056},
 {'date': 1647302400, 'tvl': 4221273115},
 {'date': 1647388800, 'tvl': 4170711031},
 {'date': 1647475200, 'tvl': 4205653757},
 {'date': 1647561600, 'tvl': 4109065053},
 {'date': 1647648000, 'tvl': 4387202498},
 {'date': 1647734400, 'tvl': 4324845347},
 {'date': 1647820800, 'tvl': 4223037741},
 {'date': 1647907200, 'tvl': 4241576802},
 {'date': 1647993600, 'tvl': 4091108110},
 {'date': 1648080000, 'tvl': 4121617332},
 {'date': 1648166400, 'tvl': 4148626289},
 {'date': 1648252800, 'tvl': 4068416159},
 {'date': 1648339200, 'tvl': 4302593105},
 {'date': 1648425600, 'tvl': 4249579831},
 {'date': 1648512000, 'tvl': 4337223936},
 {'date': 1648598400, 'tvl': 4273232601},
 {'date': 1648684800, 'tvl': 4447464439},
 {'date': 1648771200, 'tvl': 4481773935},
 {'date': 1648857600, 'tvl': 4731102037},
 {'date': 1648944000, 'tvl': 4731619939},
 {'date': 1649030400, 'tvl': 4808549261},
 {'date': 1649116800, 'tvl': 4825021968},
 {'date': 1649203200, 'tvl': 4596447269},
 {'date': 1649289600, 'tvl': 4381090584},
 {'date': 1649376000, 'tvl': 4024894118},
 {'date': 1649462400, 'tvl': 4053305493},
 {'date': 1649548800, 'tvl': 4106559764},
 {'date': 1649635200, 'tvl': 4075997437},
 {'date': 1649721600, 'tvl': 3850908985},
 {'date': 1649808000, 'tvl': 3860577821},
 {'date': 1649894400, 'tvl': 4089541250},
 {'date': 1649980800, 'tvl': 3971780747},
 {'date': 1650067200, 'tvl': 4027227902},
 {'date': 1650153600, 'tvl': 3975970069},
 {'date': 1650240000, 'tvl': 3890719398},
 {'date': 1650326400, 'tvl': 4059997833},
 {'date': 1650412800, 'tvl': 4103747231},
 {'date': 1650499200, 'tvl': 4016856795},
 {'date': 1650585600, 'tvl': 3952371780},
 {'date': 1650672000, 'tvl': 3842766127},
 {'date': 1650758400, 'tvl': 3965697713},
 {'date': 1650844800, 'tvl': 3806204017},
 {'date': 1650931200, 'tvl': 3948776649},
 {'date': 1651017600, 'tvl': 3767772455},
 {'date': 1651104000, 'tvl': 3899913937},
 {'date': 1651190400, 'tvl': 3882353190},
 {'date': 1651276800, 'tvl': 3838258579},
 {'date': 1651363200, 'tvl': 3555628093},
 {'date': 1651449600, 'tvl': 3632275189},
 {'date': 1651536000, 'tvl': 3644027511},
 {'date': 1651622400, 'tvl': 3654803356},
 {'date': 1651708800, 'tvl': 3775014567},
 {'date': 1651795200, 'tvl': 3607987045},
 {'date': 1651881600, 'tvl': 3575335096},
 {'date': 1651968000, 'tvl': 3531183252},
 {'date': 1652054400, 'tvl': 3406626647},
 {'date': 1652140800, 'tvl': 2977807176},
 {'date': 1652227200, 'tvl': 3013958516},
 {'date': 1652313600, 'tvl': 2646294386},
 {'date': 1652400000, 'tvl': 2504459607},
 {'date': 1652486400, 'tvl': 2507642131},
 {'date': 1652572800, 'tvl': 2573223090},
 {'date': 1652659200, 'tvl': 2736899436},
 {'date': 1652745600, 'tvl': 2709082290},
 {'date': 1652832000, 'tvl': 2760557698},
 {'date': 1652918400, 'tvl': 2689164260},
 {'date': 1653004800, 'tvl': 2752041452},
 {'date': 1653091200, 'tvl': 2611117390},
 {'date': 1653177600, 'tvl': 2646259317},
 {'date': 1653264000, 'tvl': 2701752751},
 {'date': 1653350400, 'tvl': 2690204545},
 {'date': 1653436800, 'tvl': 2645229346},
 {'date': 1653523200, 'tvl': 2627012059},
 {'date': 1653609600, 'tvl': 2544374976},
 {'date': 1653696000, 'tvl': 2435185793},
 {'date': 1653782400, 'tvl': 2476559893},
 {'date': 1653868800, 'tvl': 2512781627},
 {'date': 1653955200, 'tvl': 2520917517},
 {'date': 1654041600, 'tvl': 2511483227},
 {'date': 1654128000, 'tvl': 2440606912},
 {'date': 1654214400, 'tvl': 2372493131},
 {'date': 1654300800, 'tvl': 2399596224},
 {'date': 1654387200, 'tvl': 2395477474},
 {'date': 1654473600, 'tvl': 2339879041},
 {'date': 1654560000, 'tvl': 2366949034},
 {'date': 1654646400, 'tvl': 2356903833},
 {'date': 1654732800, 'tvl': 2487731837},
 {'date': 1654819200, 'tvl': 2461343569},
 {'date': 1654905600, 'tvl': 2409347919},
 {'date': 1654992000, 'tvl': 2276101238},
 {'date': 1655078400, 'tvl': 2094418261},
 {'date': 1655164800, 'tvl': 1899145885},
 {'date': 1655251200, 'tvl': 1898304377},
 {'date': 1655337600, 'tvl': 1791545957},
 {'date': 1655424000, 'tvl': 1601845745},
 {'date': 1655510400, 'tvl': 1690729234},
 {'date': 1655596800, 'tvl': 1606205418},
 {'date': 1655683200, 'tvl': 1647931629},
 {'date': 1655769600, 'tvl': 1630951494},
 {'date': 1655856000, 'tvl': 1646436945},
 {'date': 1655942400, 'tvl': 1632932359},
 {'date': 1656028800, 'tvl': 1658645227},
 {'date': 1656115200, 'tvl': 1714779635},
 {'date': 1656201600, 'tvl': 1717098543},
 {'date': 1656288000, 'tvl': 1664372611},
 {'date': 1656374400, 'tvl': 1673138874},
 {'date': 1656460800, 'tvl': 1656030879},
 {'date': 1656547200, 'tvl': 1607607784},
 {'date': 1656633600, 'tvl': 1558848755},
 {'date': 1656720000, 'tvl': 1532175498},
 {'date': 1656806400, 'tvl': 1571752658},
 {'date': 1656892800, 'tvl': 1579477582},
 {'date': 1656979200, 'tvl': 1599575859},
 {'date': 1657065600, 'tvl': 1580541536},
 {'date': 1657152000, 'tvl': 1652542224},
 {'date': 1657238400, 'tvl': 1729678199},

In [4]:
# Since the data has no extra 'fluff' in the top of the raw json, can just load directly into a dataframe:
df_sol = pd.DataFrame(solana_data)

# The timestamps are in UNIX, so need to convert to datetime in a human-readable format, then set as the index and sort by the date:

df_sol['date'] = pd.to_datetime(df_sol['date'], unit='s')
df_sol.set_index('date', inplace=True)
df_sol.sort_index(inplace=True)

# Take a look at the df from a few angles:
print(df_sol.shape)
print(df_sol.info())

df_sol.head(3)

(1779, 1)
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1779 entries, 2021-03-18 to 2026-01-29
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tvl     1779 non-null   int64
dtypes: int64(1)
memory usage: 27.8 KB
None

                  tvl
date
2021-03-18  148988798
2021-03-19  153204289
2021-03-20  147690914

In [11]:
# Can see all of the protocols available:
llama.get_all_protocols()

[{'id': '2269',
  'name': 'Binance CEX',
  'address': None,
  'symbol': '-',
  'url': 'https://www.binance.com',
  'description': 'Binance is a cryptocurrency exchange which is the largest exchange in the world in terms of daily trading volume of cryptocurrencies',
  'chain': 'Multi-Chain',
  'logo': 'https://icons.llama.fi/binance-cex.jpg',
  'audits': '0',
  'gecko_id': 'binancecoin',
  'cmcId': None,
  'category': 'CEX',
  'chains': ['Ethereum',
   'Bitcoin',
   'Binance',
   'Ripple',
   'Tron',
   'Solana',
   'Doge',
   'Arbitrum',
   'Base',
   'Avalanche',
   'Litecoin',
   'TON',
   'Hedera',
   'Near',
   'Polygon',
   'Aptos',
   'Optimism',
   'Chiliz',
   'Sonic',
   'Plasma',
   'Op_Bnb',
   'Stellar',
   'Algorand',
   'Celo',
   'Ronin',
   'zkSync Era',
   'Manta',
   'Starknet',
   'Scroll',
   'Polkadot',
   'Sui',
   'Fantom'],
  'module': 'binance/index.js',
  'twitter': 'binance',
  'listedAt': 1668170565,
  'methodology': 'We collect the wallets from this Binance blog post https://www.binance.com/en/blog/community/our-commitment-to-transparency-2895840147147652626. We are not counting the Binance Recovery Fund wallet. On Ethereum, we also include staked ETH tracked via known withdrawal addresses.',
  'misrepresentedTokens': False,
  'slug': 'binance-cex',
  'tvl': 166685307660.641,
  'chainTvls': {'Fantom': 0,
   'Solana': 2301934097.532098,
   'Chiliz': 95377180.05979536,
   'Sonic': 60603223.246177435,
   'Plasma': 54556503.47745615,
   'Scroll': 3068.6955025022853,
   'Op_Bnb': 52352700.01265123,
   'Manta': 1316254.95702055,
   'Base': 612471121.2560234,
   'Hedera': 290040972.86902636,
   'zkSync Era': 4975798.768976127,
   'Starknet': 434441.93855831254,
   'Optimism': 114474595.81747586,
   'Sui': 6.707554015590051,
   'Ronin': 5447815.653250086,
   'Algorand': 36902652.57496386,
   'Celo': 18479724.124996737,
   'Arbitrum': 616780255.8019412,
   'Stellar': 49951471.06502732,
   'Polygon': 226401539.2406497,
   'Litecoin': 501408123.8271411,
   'Avalanche': 610998580.3229669,
   'Near': 228512935.27328628,
   'Ethereum': 60731290577.79982,
   'Binance': 36608979952.33818,
   'Polkadot': 953.7265767109113,
   'Tron': 2941104286.5784545,
   'Aptos': 217605533.48155105,
   'TON': 415841084.66510546,
   'Ripple': 4698003300.806564,
   'Bitcoin': 53054705559.65666,
   'Doge': 2134353348.3655474},
  'change_1h': -0.17829404534123228,
  'change_1d': -0.6655886399706219,
  'change_7d': -5.166506084811786,
  'tokenBreakdowns': {},
  'mcap': 121103104735.83682},
 {'id': '1599',
  'name': 'Aave V3',
  'address': '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
  'symbol': 'AAVE',
  'url': 'https://aave.com',
  'description': 'Earn interest, borrow assets, and build applications',
  'chain': 'Multi-Chain',
  'logo': 'https://icons.llama.fi/aave-v3.png',
  'audits': '2',
  'gecko_id': None,
  'cmcId': None,
  'category': 'Lending',
  'chains': ['Ethereum',
   'Plasma',
   'Arbitrum',
   'Base',
   'Avalanche',
   'Binance',
   'Polygon',
   'Linea',
   'Optimism',
   'xDai',
   'Sonic',
   'Celo',
   'Scroll',
   'zkSync Era',
   'Soneium',
   'Metis',
   'Fantom',
   'Harmony'],
  'oraclesBreakdown': [{'name': 'Chainlink', 'type': 'Primary', 'proof': []}],
  'module': 'aave-v3/index.js',
  'twitter': 'aave',
  'audit_links': ['https://aave.com/security'],
  'listedAt': 1648776877,
  'parentProtocol': 'parent#aave',
  'wrongLiquidity': True,
  'dimensions': {'fees': {'genuineSpikes': ['1722816000', '1738540800'],
    'adapter': 'aave-v3'}},
  'methodology': "Counts the tokens locked in the contracts to be used as collateral to borrow or to earn yield. Borrowed coins are not counted towards the TVL, so only the coins actually locked in the contracts are counted. There's multiple reasons behind this but one of the main ones is to avoid inflating the TVL through cycled lending.",
  'misrepresentedTokens': False,
  'hallmarks': [[1650471689, 'Start AVAX Rewards'],
   [1659630089, 'Start OP Rewards']],
  'slug': 'aave-v3',
  'tvl': 32576838339.159916,
  'chainTvls': {'Base': 878864479.0308338,
   'Soneium-borrowed': 388556.2774100136,
   'Base-borrowed': 582399276.0025083,
   'Scroll-borrowed': 5757020.160282223,
   'Linea-borrowed': 68450029.61423679,
   'Sonic-borrowed': 10484174.983536325,
   'Arbitrum-borrowed': 822994870.2029362,
   'Binance-borrowed': 99828483.07522051,
   'Soneium': 2926828.0705872895,
   'zkSync Era-borrowed': 2020568.15911574,
   'Plasma': 2708641922.789033,
   'Fantom': 7218.897723903765,
   'Ethereum-borrowed': 19303828857.612278,
   'Celo': 14615893.474055447,
   'Celo-borrowed': 5881409.003209302,
   'Binance': 247255752.56562528,
   'Linea': 96313661.89458929,
   'xDai': 81379684.50655122,
   'Polygon-borrowed': 84905421.14097445,
   'Scroll': 10707379.827422122,
   'xDai-borrowed': 32684256.419612657,
   'Arbitrum': 1134773063.5599344,
   'Sonic': 28208961.610032126,
   'Plasma-borrowed': 1987972209.5254796,
   'Ethereum': 26534788003.52958,
   'Metis-borrowed': 359320.9766268108,
   'Harmony-borrowed': 459811.2727709141,
   'Polygon': 188589906.3049707,
   'zkSync Era': 5285922.26977995,
   'Optimism': 89012342.94801648,
   'Avalanche': 554120350.0639127,
   'Optimism-borrowed': 47172196.41634251,
   'Metis': 1346967.8172726708,
   'Avalanche-borrowed': 323595921.12429756,
   'Fantom-borrowed': 1603.6558125679637,
   'Harmony': 0,
   'borrowed': 23379183985.62265},
  'change_1h': -0.11905223706806112,
  'change_1d': 0.8367277425334976,
  'change_7d': -7.764162027880616,
  'tokenBreakdowns': {},
  'mcap': None,
  'parentProtocolSlug': 'aave'},
 {'id': '182',
  'name': 'Lido',
  'address': '0x5a98fcbea516cf06857215779fd812ca3bef1b32',
  'symbol': 'LDO',
  'url': 'https://lido.fi/',
  'referralUrl': 'https://stake.lido.fi/?ref=0x08a3c2A819E3de7ACa384c798269B3Ce1CD0e437',
  'description': 'Liquid staking for Ethereum and Polygon. Daily staking rewards, no lock ups.',
  'chain': 'Multi-Chain',
  'logo': 'https://icons.llama.fi/lido.png',
  'audits': '2',
  'gecko_id': 'lido-dao',
  'cmcId': '8000',
  'category': 'Liquid Staking',
  'chains': ['Ethereum', 'Solana', 'Moonbeam', 'Moonriver', 'Terra'],
  'module': 'lido/index.js',
  'treasury': 'lido.js',
  'twitter': 'LidoFinance',
  'audit_links': ['https://github.com/lidofinance/audits'],
  'openSource': True,
  'governanceID': ['snapshot:lido-snapshot.eth'],
  'github': ['lidofinance'],
  'dimensions': {'fees': 'lido'},
  'methodology': 'Staked tokens are counted as TVL based on the chain that they are staked on and where the liquidity tokens are issued, stMATIC is counted as Ethereum TVL since MATIC is staked in Ethereum and the liquidity token is also issued on Ethereum',
  'misrepresentedTokens': False,
  'hallmarks': [[1610496000, 'Start of incentives for curve pool'],
   [1651881600, 'UST depeg'],
   [1654822801, 'stETH depeg'],
   [1667865600, 'FTX collapse'],
   [1684108800, 'ETH Withdrawal Activation']],
  'slug': 'lido',
  'tvl': 27502508972.905987,
  'chainTvls': {'Terra': 0,
   'Ethereum': 27495963958.26582,
   'Moonriver': 16110.332226523778,
   'Moonbeam': 55129.56680195464,
   'Solana': 6473774.741138908},
  'change_1h': 0.43544701644783856,
  'change_1d': 2.0850565229308557,
  'change_7d': -6.4924999301185835,
  'tokenBreakdowns': {},
  'mcap': 442047479.51185006},
 {'id': '2272',
  'name': 'OKX',
  'address': None,
  'symbol': '-',
  'url': 'https://www.okx.com',
  'description': 'OKX, formerly known as OKEx, is a Seychelles-based cryptocurrency exchange and derivatives exchange that provides a platform for trading various instruments such as spot and derivative',
  'chain': 'Multi-Chain',
  'logo': 'https://icons.llama.fi/okx.jpg',
  'audits': '0',
  'gecko_id': 'okb',
  'cmcId': None,
  'category': 'CEX',
  'chains': ['Ethereum',
   'Bitcoin',
   'Solana',
   'Doge',
   'Tron',
   'Litecoin',
   'Ripple',
   'Aptos',
   'Linea',
   'Arbitrum',
   'Optimism',
   'TON',
   'Base',
   'zkSync Era',
   'Starknet',
   'Scroll',
   'Avalanche',
   'Polygon',
   'Polkadot'],
  'module': 'okex/index.js',
  'twitter': 'okx',
  'listedAt': 1668185769,
  'misrepresentedTokens': False,
  'slug': 'okx',
  'tvl': 22532268735.01441,
  'chainTvls': {'Scroll': 37504.19968808159,
   'Optimism': 20066395.539790127,
   'Base': 4001376.1812810176,
   'zkSync Era': 743269.6047703936,
   'Avalanche': 134.0426972538609,
   'Starknet': 52421.82363100062,
   'Linea': 23897011.104006387,
   'Arbitrum': 22706816.108675223,
   'Polygon': 3.2131939971299084,
   'Polkadot': 0,
   'Doge': 415041418.2322818,
   'Ethereum': 11324193497.102034,
   'Solana': 685057089.859381,
   'Aptos': 28034698.073073857,
   'Tron': 338092139.88212883,
   'Ripple': 141563763.90955994,
   'Litecoin': 170774156.03552926,
   'Bitcoin': 9349268432.787369,
   'TON': 8738607.315317707},
  'change_1h': 0.18517427629561212,
  'change_1d': 1.1731304743357214,
  'change_7d': -4.345958631343862,
  'tokenBreakdowns': {},
  'mcap': 2162985787.2066674},
 {'id': '2275',
  'name': 'Bitfinex',
  'address': None,
  'symbol': '-',
  'url': 'https://www.bitfinex.com',
  'description': 'Bitfinex facilitates a graphical trading experience with advanced charting functionality that allows traders to visualise orders, positions and price alerts',
  'chain': 'Multi-Chain',
  'logo': 'https://icons.llama.fi/bitfinex.png',
  'audits': '0',
  'gecko_id': None,
  'cmcId': None,
  'category': 'CEX',
  'chains': ['Bitcoin',
   'Ethereum',
   'Solana',
   'Tron',
   'Avalanche',
   'Polygon',
   'Tezos',
   'Near',
   'Cosmos',
   'Algorand',
   'EOS',
   'Aptos',
   'Elrond',
   'Cardano',
   'EthereumClassic',
   'Fantom',
   'Zilliqa',
   'Litecoin',
   'Doge',
   'Polkadot'],
  'module': 'bitfinex/index.js',
  'twitter': 'bitfinex',
  'listedAt': 1668201923,
  'misrepresentedTokens': False,
  'slug': 'bitfinex',
  'tvl': 20102403784.652103,
  'chainTvls': {'Zilliqa': 0,
   'Litecoin': 0,
   'Doge': 0,
   'Fantom': 0.015135621026254613,
   'Cardano': 0.4546786565964544,
   'Elrond': 179621.46999824073,
   'Ethereum': 6933378093.414201,
   'Near': 1496543.7418985874,
   'EthereumClassic': 0.11008088716184551,
   'Algorand': 868289.7327770249,
   'Polkadot': 0,
   'Aptos': 474633.27066617383,
   'Cosmos': 1143444.545502972,
   'Polygon': 3676673.622477617,
   'Tezos': 2414422.55999715,
   'Avalanche': 17321730.038764134,
   'EOS': 684928.3071151656,
   'Tron': 191389524.56199405,
   'Solana': 425045744.9391962,
   'Bitcoin': 12524330133.86762},
  'change_1h': 0.026961396987900343,
  'change_1d': 0.33065375054506774,
  'change_7d': -4.078177191828601,
  'tokenBreakdowns': {},
  'mcap': None},
 {'id': '2286',
  'name': 'Bybit',
  'address': None,
  'symbol': '-',
  'url': 'https://www.bybit.com',
  'description': 'Crypto trading experience elevated. Buy, sell, trade BTC, altcoins & NFTs. Get access to the spot and futures market or stake your coins securely.',
  'chain': 'Multi-Chain',
  'logo': 'https://icons.llama.fi/bybit.png',
  'audits': '0',
  'gecko_id': None,
  'cmcId': None,
  'category': 'CEX',
  'chains': ['Ethereum',
   'Bitcoin',
   'Tron',
   'Solana',
   'Mantle',
   'Ripple',
   'Binance',
   'Avalanche',
   'Doge',
   'Aptos',
   'Polygon',
   'Arbitrum',
   'Hyperliquid L1',
   'Optimism',
   'Base',
   'Linea',
   'Klaytn',
   'Kava',
   'zkSync Era',
   'Cardano',
   'Cosmos',
   'TON',
   'dYdX',
   'Sonic',
   'Arbitrum Nova',
   'Celo',
   'Plasma',
   'EOS',
   'Manta',
   'Starknet',
   'Scroll',
   'Taiko',
   'Fantom',
   'Polkadot',
   'Litecoin'],
  'module': 'bybit/index.js',
  'twitter': 'Bybit_Official',
  'listedAt': 1668595021,
  'misrepresentedTokens': False,
  'slug': 'bybit',
  'tvl': 18497978493.918858,
  'chainTvls': {'Base': 33845375.637208186,
   'Cardano': 19614717.40183825,
   'Fantom': 9.995406035183718,
   'Manta': 85066.61825047586,
   'Plasma': 2172539.4503419474,
   'Taiko': 4962.427078866709,
   'Scroll': 36563.04845367732,
   'Polkadot': 0,
   'Hyperliquid L1': 43620810.283702865,
   'Starknet': 74399.56915674376,
   'Sonic': 7832543.778374924,
   'dYdX': 7907307.750333703,
   'Aptos': 127157088.35440117,
   'Linea': 32753668.31392952,
   'Avalanche': 189294823.71567836,
   'zkSync Era': 22457284.10087455,
   'Optimism': 41398607.20457972,
   'Kava': 26040755.626819983,
   'Arbitrum Nova': 3787878.290687368,
   'Cosmos': 14486863.635781284,
   'Arbitrum': 57803763.31932843,
   'Litecoin': 0,
   'Klaytn': 27748107.373564962,
   'Mantle': 653981766.0451052,
   'Celo': 3554510.886877892,
   'EOS': 1892010.1414427902,
   'Polygon': 62580891.96934759,
   'Binance': 372416143.3584867,
   'Ethereum': 7994939438.051774,
   'Solana': 956264621.7346613,
   'Ripple': 468675895.0423115,
   'Doge': 163223532.88497,
   'Tron': 1771151697.738908,
   'Bitcoin': 5379663003.233288,
   'TON': 11511846.935893321},
  'change_1h': -0.07587122434766513,
  'change_1d': -0.4294859537358491,
  'change_7d': -4.040741475714469,
  'tokenBreakdowns': {},
  'mcap': None},
 {'id': '3732',
  'name': 'Robinhood',
  'address': None,
  'symbol': '-',
  'url': 'https://robinhood.com',
  'description': 'Democratizing finance for all. Crypto trading: Robinhood Crypto.',
  'chain': 'Multi-Chain',
  'logo': 'https://icons.llama.fi/robinhood.jpg',
  'audits': '0',
  'gecko_id': None,
  'cmcId': None,
  'category': 'CEX',
  'chains': ['Bitcoin', 'Ethereum', 'Avalanche', 'Polygon'],
  'module': 'robinhood/index.js',
  'twitter': 'RobinhoodApp',
  'github': ['robinhood'],
  'misrepresentedTokens': False,
  'slug': 'robinhood',
  'tvl': 16586956747.420147,
  'chainTvls': {'Polygon': 9097.107113783788,
   'Avalanche': 50601358.449145146,
   'Ethereum': 3918742199.4632854,
   'Bitcoin': 12617604092.400602},
  'change_1h': 0.560846055762724,
  'change_1d': -0.7564448204547745,
  'change_7d': -7.089930980240226,
  'tokenBreakdowns': {},
  'mcap': None},
 {'id': '3107',
  'name': 'EigenCloud',
  'previousNames': ['EigenLayer'],
  'address': '0xec53bf9167f50cdeb3ae105f56099aaab9061f83',
  'symbol': 'EIGEN',
  'url': 'https://www.eigencloud.xyz',
  'description': 'EigenCloud is a protocol built on Ethereum that introduces restaking, a new primitive in cryptoeconomic security. This primitive enables the reuse of ETH on the consensus layer',
  'chain': 'Ethereum',
  'logo': 'https://icons.llama.fi/eigencloud.png',
  'audits': '2',
  'gecko_id': 'eigenlayer',
  'cmcId': '30494',
  'category': 'Restaking',
  'chains': ['Ethereum'],
  'module': 'eigenlayer/index.js',
  'twitter': 'eigenlayer',
  'audit_links': ['https://docs.eigencloud.xyz/eigenlayer/security/audits'],
  'github': ['Layr-Labs'],
  'listedAt': 1686776222,
  'dimensions': {'fees': {'genuineSpikes': ['1729209600'],
    'adapter': 'eigenlayer'}},
  'misrepresentedTokens': False,
  'slug': 'eigencloud',
  'tvl': 13172129174.404835,
  'chainTvls': {'Ethereum-staking': 152696391.78585187,
   'Ethereum': 13172129174.404835,
   'staking': 152696391.78585187},
  'change_1h': 0.41503383768667845,
  'change_1d': 2.718720093715433,
  'change_7d': -7.544792105052281,
  'tokenBreakdowns': {},
  'mcap': 180616753.3070084,
  'staking': 152696391.78585187},
 {'id': '2',
  'name': 'WBTC',
  'address': None,
  'symbol': '-',
  'url': 'https://wbtc.network/',
  'description': 'Wrapped Bitcoin (WBTC) is the first ERC20 token backed 1:1 with Bitcoin.Completely transparent. 100% verifiable. Community led.',
  'chain': 'Bitcoin',
  'logo': 'https://icons.llama.fi/wbtc.png',
  'audits': '2',
  'gecko_id': None,
  'cmcId': None,
  'category': 'Bridge',
  'chains': ['Bitcoin'],
  'module': 'wbtc.js',
  'twitter': 'WrappedBTC',
  'audit_links': ['https://wbtc.network/dashboard/audit'],
  'github': ['WrappedBTC'],
  'dimensions': {'fees': 'wbtc'},
  'methodology': 'TVL for WBTC consists of the BTC deposits in custody that were used to mint WBTC',
  'misrepresentedTokens': False,
  'slug': 'wbtc',
  'tvl': 11118988631.746655,
  'chainTvls': {'Bitcoin': 11118988631.746655},
  'change_1h': 0.6010065847850825,
  'change_1d': 1.3795424309533928,
  'change_7d': -6.044047232414144,
  'tokenBreakdowns': {},
  'mcap': None},
 {'id': '2914',
  'name': 'Binance staked ETH',
  'address': None,
  'symbol': '-',
  'assetToken': 'WBETH',
  'url': 'https://www.binance.com/en/wbeth',
  'description': 'A token created by depositing BETH into the BETH wrapper. Each WBETH represents 1 BETH (1:1 to staked ETH) plus all of its accrued ETH2.0 staking rewards',
  'chain': 'Multi-Chain',
  'logo': 'https://icons.llama.fi/binance-staked-eth.png',
  'audits': '2',
  'gecko_id': None,
  'cmcId': None,
  'category': 'Liquid Staking',
  'chains': ['Ethereum', 'Binance'],
  'module': 'binance-staked-eth/index.js',
  'twitter': 'binance',
  'audit_links': ['https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-wBETH-v1.0.pdf'],
  'listedAt': 1682803395,
  'dimensions': {'fees': 'binance-staked-eth'},
  'misrepresentedTokens': False,
  'slug': 'binance-staked-eth',
  'tvl': 10803880816.807417,
  'chainTvls': {'Ethereum': 10192736112.64684, 'Binance': 611144704.1605769},
  'change_1h': 0.42954529028914124,
  'change_1d': -2.7389351259357824,
  'change_7d': -10.51073887044069,
  'tokenBreakdowns': {},
  'mcap': None},
 {'id': '2626',
  'name': 'ether.fi Stake',
  'address': '0xfe0c30065b384f05761f15d0cc899d4f9f9cc0eb',
  'symbol': 'ETHFI',
  'url': 'https://www.ether.fi/app/weeth',
  'description': 'Decentralized and non-custodial Ethereum staking protocol.',
  'chain': 'Multi-Chain',
  'logo': 'https://icons.llama.fi/ether.fi.jpg',
  'audits': '0',
  'gecko_id': None,
  'cmcId': None,
  'category': 'Liquid Restaking',
  'chains': ['Arbitrum', 'Ethereum', 'Base'],
  'module': 'ether-fi/index.js',
  'twitter': 'ether_fi',
  'parentProtocol': 'parent#ether-fi',
  'listedAt': 1677778460,
  'misrepresentedTokens': False,
  'slug': 'ether.fi-stake',
  'tvl': 8545032172.632374,
  'chainTvls': {'Arbitrum-staking': 1533263.7873839084,
   'Ethereum-staking': 45692950.668908,
   'Base-staking': 0,
   'Ethereum': 8545032172.632374,
   'staking': 47226214.45629191},
  'change_1h': 0.43692557497621465,
  'change_1d': -2.0816959210281425,
  'change_7d': -8.37121488929003,
  'tokenBreakdowns': {},
  'mcap': None,
  'parentProtocolSlug': 'ether.fi',
  'staking': 47226214.45629191},
 {'id': '2352',
  'name': 'Bitget',
  'address': None,
  'symbol': '-',
  'url': 'https://www.bitget.com',
  'description': 'Bitget is the leading crypto exchange platform for crypto derivatives trading.',
  'chain': 'Multi-Chain',
  'logo': 'https://icons.llama.fi/bitget.jpg',
  'audits': '0',
  'gecko_id': None,
  'cmcId': None,
  'category': 'CEX',
  'chains': ['Bitcoin',
   'Ethereum',
   'Binance',
   'Tron',
   'Solana',
   'Ripple',
   'Arbitrum',
   'Polygon',
   'Cardano',
   'Avalanche',
   'Base',
   'TON',
   'Cronos',
   'Optimism',
   'Sonic',
   'Starknet',
   'Sui',
   'Metis',
   'Klaytn',
   'zkSync Era',
   'Fantom',
   'Kava',
   'Hyperliquid L1'],
  'module': 'bitget/index.js',
  'twitter': 'bitget',
  'listedAt': 1670842933,
  'misrepresentedTokens': False,
  'slug': 'bitget',
  'tvl': 7369894031.945757,
  'chainTvls': {'Metis': 489242.99257057934,
   'Hyperliquid L1': 0,
   'Sonic': 961393.9085098368,
   'Base': 13677498.282456763,
   'zkSync Era': 385933.5431231991,
   'Starknet': 899389.0487613217,
   'Sui': 659795.6739416039,
   'Fantom': 16.239802370331788,
   'Cardano': 32236358.950127326,
   'Avalanche': 27329679.124676526,
   'Polygon': 41349201.28468578,
   'Cronos': 4590632.7531539975,
   'Arbitrum': 73300068.59867282,
   'Klaytn': 405671.0152524965,
   'Kava': 7.201296507758101,
   'Binance': 835982496.289173,
   'Ripple': 227494158.94247273,
   'Optimism': 3771250.120046716,
   'Ethereum': 2212128694.4633837,
   'Solana': 371389843.50235313,
   'Tron': 398299862.3134645,
   'TON': 10058244.16997722,
   'Bitcoin': 3114484593.527855},
  'change_1h': 0.5422063134327857,
  'change_1d': 0.16704497152014142,
  'change_7d': -1.822630109130344,
  'tokenBreakdowns': {},

In [5]:
# Just grabbing a semi-random protocol (selected Jito as it was the first well known one I could find; again, this is really for the viz, so any example with enough data should be GTG!)

response = llama.get_protocol('Jito Liquid Staking')
response

{'id': '2308',
 'name': 'Jito Liquid Staking',
 'address': 'solana:jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL',
 'symbol': 'JTO',
 'url': 'https://jito.network',
 'description': 'JitoSOL is the first liquid staking derivative on Solana to include MEV rewards. Tracks the price of SOL while accruing staking and MEV rewards. Yield is accrued in the price so it will steadily appreciate vs. SOL',
 'chain': 'Solana',
 'logo': 'https://icons.llama.fi/jito-liquid-staking.png',
 'audits': '2',
 'gecko_id': None,
 'cmcId': None,
 'category': 'Liquid Staking',
 'chains': ['Solana'],
 'module': 'jito/index.js',
 'twitter': 'jito_sol',
 'audit_links': ['https://spl.solana.com/stake-pool#security-audits',
  'https://2926710696-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2Ffrb9MGTK6eZJlEQJyylq%2Fuploads%2F1jfEDpGcd5YlnHusbKYO%2FNeodymeJito.pdf'],
 'oraclesBreakdown': [{'name': 'Switchboard',
   'type': 'Secondary',
   'proof': ['https://github.com/DefiLlama/defillama-server/pull/9193']}],
 'parentProtocol': 'parent#jito',
 'listedAt': 1669265429,
 'dimensions': {'fees': 'jito-staked-sol'},
 'methodology': 'Uses the SPL Stake Pool SDK to fetch the total supply of deposited SOL into the Jito Stake Pool',
 'chainTvls': {'Solana': {'tvl': [{'date': 1669248000,
     'totalLiquidityUSD': 4515393},
    {'date': 1669334400, 'totalLiquidityUSD': 4467877},
    {'date': 1669420800, 'totalLiquidityUSD': 4472156},
    {'date': 1669507200, 'totalLiquidityUSD': 4399198},
    {'date': 1669593600, 'totalLiquidityUSD': 4392317},
    {'date': 1669680000, 'totalLiquidityUSD': 4142618},
    {'date': 1669766400, 'totalLiquidityUSD': 4324393},
    {'date': 1669852800, 'totalLiquidityUSD': 4390935},
    {'date': 1669939200, 'totalLiquidityUSD': 4302128},
    {'date': 1670025600, 'totalLiquidityUSD': 4309009},
    {'date': 1670112000, 'totalLiquidityUSD': 4243322},
    {'date': 1670198400, 'totalLiquidityUSD': 4407707},
    {'date': 1670284800, 'totalLiquidityUSD': 4399164},
    {'date': 1670371200, 'totalLiquidityUSD': 4484583},
    {'date': 1670457600, 'totalLiquidityUSD': 4268816},
    {'date': 1670544000, 'totalLiquidityUSD': 4319294},
    {'date': 1670630400, 'totalLiquidityUSD': 4310528},
    {'date': 1670716800, 'totalLiquidityUSD': 4304179},
    {'date': 1670803200, 'totalLiquidityUSD': 4275858},
    {'date': 1670889600, 'totalLiquidityUSD': 4233306},
    {'date': 1670976000, 'totalLiquidityUSD': 4440535},
    {'date': 1671062400, 'totalLiquidityUSD': 4538885},
    {'date': 1671148800, 'totalLiquidityUSD': 4516848},
    {'date': 1671235200, 'totalLiquidityUSD': 3985342},
    {'date': 1671321600, 'totalLiquidityUSD': 3908574},
    {'date': 1671408000, 'totalLiquidityUSD': 3971922},
    {'date': 1671494400, 'totalLiquidityUSD': 4138601},
    {'date': 1671580800, 'totalLiquidityUSD': 4191780},
    {'date': 1671667200, 'totalLiquidityUSD': 4189816},
    {'date': 1671753600, 'totalLiquidityUSD': 4092360},
    {'date': 1671840000, 'totalLiquidityUSD': 4086548},
    {'date': 1671926400, 'totalLiquidityUSD': 3978657},
    {'date': 1672012800, 'totalLiquidityUSD': 3909155},
    {'date': 1672099200, 'totalLiquidityUSD': 3906607},
    {'date': 1672185600, 'totalLiquidityUSD': 3819597},
    {'date': 1672272000, 'totalLiquidityUSD': 3444372},
    {'date': 1672358400, 'totalLiquidityUSD': 3524186},
    {'date': 1672444800, 'totalLiquidityUSD': 3530888},
    {'date': 1672531200, 'totalLiquidityUSD': 3596934},
    {'date': 1672617600, 'totalLiquidityUSD': 3564319},
    {'date': 1672704000, 'totalLiquidityUSD': 4078960},
    {'date': 1672790400, 'totalLiquidityUSD': 5101239},
    {'date': 1672876800, 'totalLiquidityUSD': 4974899},
    {'date': 1672963200, 'totalLiquidityUSD': 5125932},
    {'date': 1673049600, 'totalLiquidityUSD': 5152111},
    {'date': 1673136000, 'totalLiquidityUSD': 4986457},
    {'date': 1673222400, 'totalLiquidityUSD': 5803708},
    {'date': 1673308800, 'totalLiquidityUSD': 6572910},
    {'date': 1673395200, 'totalLiquidityUSD': 6450625},
    {'date': 1673481600, 'totalLiquidityUSD': 6779156},
    {'date': 1673568000, 'totalLiquidityUSD': 6632803},
    {'date': 1673654400, 'totalLiquidityUSD': 8206393},
    {'date': 1673740800, 'totalLiquidityUSD': 9701410},
    {'date': 1673827200, 'totalLiquidityUSD': 9472812},
    {'date': 1673913600, 'totalLiquidityUSD': 9523164},
    {'date': 1674000000, 'totalLiquidityUSD': 9507575},
    {'date': 1674086400, 'totalLiquidityUSD': 8824876},
    {'date': 1674172800, 'totalLiquidityUSD': 8864465},
    {'date': 1674259200, 'totalLiquidityUSD': 10594894},
    {'date': 1674345600, 'totalLiquidityUSD': 10681060},
    {'date': 1674432000, 'totalLiquidityUSD': 10511300},
    {'date': 1674518400, 'totalLiquidityUSD': 10573732},
    {'date': 1674604800, 'totalLiquidityUSD': 10268679},
    {'date': 1674691200, 'totalLiquidityUSD': 11106531},
    {'date': 1674777600, 'totalLiquidityUSD': 10823596},
    {'date': 1674864000, 'totalLiquidityUSD': 11149033},
    {'date': 1674950400, 'totalLiquidityUSD': 11021592},
    {'date': 1675036800, 'totalLiquidityUSD': 11876266},
    {'date': 1675123200, 'totalLiquidityUSD': 10903888},
    {'date': 1675209600, 'totalLiquidityUSD': 10946142},
    {'date': 1675296000, 'totalLiquidityUSD': 11791217},
    {'date': 1675382400, 'totalLiquidityUSD': 11215780},
    {'date': 1675468800, 'totalLiquidityUSD': 11419290},
    {'date': 1675555200, 'totalLiquidityUSD': 11206875},
    {'date': 1675641600, 'totalLiquidityUSD': 10816963},
    {'date': 1675728000, 'totalLiquidityUSD': 10399150},
    {'date': 1675814400, 'totalLiquidityUSD': 11123946},
    {'date': 1675900800, 'totalLiquidityUSD': 10452770},
    {'date': 1675987200, 'totalLiquidityUSD': 9211740},
    {'date': 1676073600, 'totalLiquidityUSD': 9249028},
    {'date': 1676160000, 'totalLiquidityUSD': 9330099},
    {'date': 1676246400, 'totalLiquidityUSD': 9651211},
    {'date': 1676332800, 'totalLiquidityUSD': 9464151},
    {'date': 1676419200, 'totalLiquidityUSD': 9813650},
    {'date': 1676505600, 'totalLiquidityUSD': 10743922},
    {'date': 1676592000, 'totalLiquidityUSD': 10385995},
    {'date': 1676678400, 'totalLiquidityUSD': 10816323},
    {'date': 1676764800, 'totalLiquidityUSD': 11087942},
    {'date': 1676851200, 'totalLiquidityUSD': 11561681},
    {'date': 1676937600, 'totalLiquidityUSD': 12451112},
    {'date': 1677024000, 'totalLiquidityUSD': 11721564},
    {'date': 1677110400, 'totalLiquidityUSD': 12309910},
    {'date': 1677196800, 'totalLiquidityUSD': 11670329},
    {'date': 1677283200, 'totalLiquidityUSD': 11746359},
    {'date': 1677369600, 'totalLiquidityUSD': 11319957},
    {'date': 1677456000, 'totalLiquidityUSD': 11694508},
    {'date': 1677542400, 'totalLiquidityUSD': 11327795},
    {'date': 1677628800, 'totalLiquidityUSD': 10912399},
    {'date': 1677715200, 'totalLiquidityUSD': 11275146},
    {'date': 1677801600, 'totalLiquidityUSD': 11013032},
    {'date': 1677888000, 'totalLiquidityUSD': 10793364},
    {'date': 1677974400, 'totalLiquidityUSD': 10658796},
    {'date': 1678060800, 'totalLiquidityUSD': 10074314},
    {'date': 1678147200, 'totalLiquidityUSD': 9902108},
    {'date': 1678233600, 'totalLiquidityUSD': 9757720},
    {'date': 1678320000, 'totalLiquidityUSD': 8894655},
    {'date': 1678406400, 'totalLiquidityUSD': 8207790},
    {'date': 1678492800, 'totalLiquidityUSD': 8707881},
    {'date': 1678579200, 'totalLiquidityUSD': 8581882},
    {'date': 1678665600, 'totalLiquidityUSD': 9706203},
    {'date': 1678752000, 'totalLiquidityUSD': 9777857},
    {'date': 1678838400, 'totalLiquidityUSD': 10001689},
    {'date': 1678924800, 'totalLiquidityUSD': 9259696},
    {'date': 1679011200, 'totalLiquidityUSD': 9838472},
    {'date': 1679097600, 'totalLiquidityUSD': 11164056},
    {'date': 1679184000, 'totalLiquidityUSD': 11060850},
    {'date': 1679270400, 'totalLiquidityUSD': 11247889},
    {'date': 1679356800, 'totalLiquidityUSD': 11568240},
    {'date': 1679443200, 'totalLiquidityUSD': 11480969},
    {'date': 1679529600, 'totalLiquidityUSD': 11132993},
    {'date': 1679616000, 'totalLiquidityUSD': 11650919},
    {'date': 1679702400, 'totalLiquidityUSD': 11817085},
    {'date': 1679788800, 'totalLiquidityUSD': 11741482},
    {'date': 1679875200, 'totalLiquidityUSD': 11684818},
    {'date': 1679961600, 'totalLiquidityUSD': 11573146},
    {'date': 1680048000, 'totalLiquidityUSD': 11316948},
    {'date': 1680134400, 'totalLiquidityUSD': 11645357},
    {'date': 1680220800, 'totalLiquidityUSD': 11726123},
    {'date': 1680307200, 'totalLiquidityUSD': 12213440},
    {'date': 1680393600, 'totalLiquidityUSD': 12074563},
    {'date': 1680480000, 'totalLiquidityUSD': 11825362},
    {'date': 1680566400, 'totalLiquidityUSD': 11775258},
    {'date': 1680652800, 'totalLiquidityUSD': 12269270},
    {'date': 1680739200, 'totalLiquidityUSD': 12012724},
    {'date': 1680825600, 'totalLiquidityUSD': 11971773},
    {'date': 1680912000, 'totalLiquidityUSD': 11770798},
    {'date': 1680998400, 'totalLiquidityUSD': 11721822},
    {'date': 1681084800, 'totalLiquidityUSD': 12071440},
    {'date': 1681171200, 'totalLiquidityUSD': 12504989},
    {'date': 1681257600, 'totalLiquidityUSD': 14040373},
    {'date': 1681344000, 'totalLiquidityUSD': 14310605},
    {'date': 1681430400, 'totalLiquidityUSD': 14839789},
    {'date': 1681516800, 'totalLiquidityUSD': 14814088},
    {'date': 1681603200, 'totalLiquidityUSD': 14595293},
    {'date': 1681689600, 'totalLiquidityUSD': 15097351},
    {'date': 1681776000, 'totalLiquidityUSD': 14730764},
    {'date': 1681862400, 'totalLiquidityUSD': 15037095},
    {'date': 1681948800, 'totalLiquidityUSD': 13870665},
    {'date': 1682035200, 'totalLiquidityUSD': 13484807},
    {'date': 1682121600, 'totalLiquidityUSD': 12656291},
    {'date': 1682208000, 'totalLiquidityUSD': 12905574},
    {'date': 1682294400, 'totalLiquidityUSD': 12996616},
    {'date': 1682380800, 'totalLiquidityUSD': 12805195},
    {'date': 1682467200, 'totalLiquidityUSD': 13125143},
    {'date': 1682553600, 'totalLiquidityUSD': 13194539},
    {'date': 1682640000, 'totalLiquidityUSD': 13469962},
    {'date': 1682726400, 'totalLiquidityUSD': 14020882},
    {'date': 1682812800, 'totalLiquidityUSD': 14000963},
    {'date': 1682899200, 'totalLiquidityUSD': 13808099},
    {'date': 1682985600, 'totalLiquidityUSD': 13702583},
    {'date': 1683072000, 'totalLiquidityUSD': 13827842},
    {'date': 1683158400, 'totalLiquidityUSD': 14145186},
    {'date': 1683244800, 'totalLiquidityUSD': 13853811},
    {'date': 1683331200, 'totalLiquidityUSD': 14656959},
    {'date': 1683417600, 'totalLiquidityUSD': 14005561},
    {'date': 1683504000, 'totalLiquidityUSD': 13863598},
    {'date': 1683590400, 'totalLiquidityUSD': 13067530},
    {'date': 1683676800, 'totalLiquidityUSD': 13229868},
    {'date': 1683763200, 'totalLiquidityUSD': 13184979},
    {'date': 1683849600, 'totalLiquidityUSD': 12879807},
    {'date': 1683936000, 'totalLiquidityUSD': 13324136},
    {'date': 1684022400, 'totalLiquidityUSD': 13234853},
    {'date': 1684108800, 'totalLiquidityUSD': 13204766},
    {'date': 1684195200, 'totalLiquidityUSD': 13456436},
    {'date': 1684281600, 'totalLiquidityUSD': 13307939},
    {'date': 1684368000, 'totalLiquidityUSD': 13469161},
    {'date': 1684454400, 'totalLiquidityUSD': 13152119},
    {'date': 1684540800, 'totalLiquidityUSD': 13078085},
    {'date': 1684627200, 'totalLiquidityUSD': 13150669},
    {'date': 1684713600, 'totalLiquidityUSD': 12612112},
    {'date': 1684800000, 'totalLiquidityUSD': 12648017},
    {'date': 1684886400, 'totalLiquidityUSD': 12942196},
    {'date': 1684972800, 'totalLiquidityUSD': 12470009},
    {'date': 1685059200, 'totalLiquidityUSD': 12710086},
    {'date': 1685145600, 'totalLiquidityUSD': 12804139},
    {'date': 1685232000, 'totalLiquidityUSD': 13701561},
    {'date': 1685318400, 'totalLiquidityUSD': 13837365},
    {'date': 1685404800, 'totalLiquidityUSD': 13602875},
    {'date': 1685491200, 'totalLiquidityUSD': 14107472},
    {'date': 1685577600, 'totalLiquidityUSD': 13747677},
    {'date': 1685664000, 'totalLiquidityUSD': 13617171},
    {'date': 1685750400, 'totalLiquidityUSD': 14088988},
    {'date': 1685836800, 'totalLiquidityUSD': 14021244},
    {'date': 1685923200, 'totalLiquidityUSD': 14579670},
    {'date': 1686009600, 'totalLiquidityUSD': 13248749},
    {'date': 1686096000, 'totalLiquidityUSD': 13554199},
    {'date': 1686182400, 'totalLiquidityUSD': 12218944},
    {'date': 1686268800, 'totalLiquidityUSD': 12239559},
    {'date': 1686355200, 'totalLiquidityUSD': 11060098},
    {'date': 1686441600, 'totalLiquidityUSD': 10104910},
    {'date': 1686528000, 'totalLiquidityUSD': 10093643},
    {'date': 1686614400, 'totalLiquidityUSD': 9908603},
    {'date': 1686700800, 'totalLiquidityUSD': 9902812},
    {'date': 1686787200, 'totalLiquidityUSD': 9642999},
    {'date': 1686873600, 'totalLiquidityUSD': 9680215},
    {'date': 1686960000, 'totalLiquidityUSD': 10055613},
    {'date': 1687046400, 'totalLiquidityUSD': 10238787},
    {'date': 1687132800, 'totalLiquidityUSD': 10891437},
    {'date': 1687219200, 'totalLiquidityUSD': 11440965},
    {'date': 1687305600, 'totalLiquidityUSD': 11083132},
    {'date': 1687392000, 'totalLiquidityUSD': 12564411},
    {'date': 1687478400, 'totalLiquidityUSD': 11972229},
    {'date': 1687564800, 'totalLiquidityUSD': 12532924},
    {'date': 1687651200, 'totalLiquidityUSD': 12027802},
    {'date': 1687737600, 'totalLiquidityUSD': 12175847},
    {'date': 1687824000, 'totalLiquidityUSD': 11784051},
    {'date': 1687910400, 'totalLiquidityUSD': 11823570},
    {'date': 1687996800, 'totalLiquidityUSD': 11547985},
    {'date': 1688083200, 'totalLiquidityUSD': 13225078},
    {'date': 1688169600, 'totalLiquidityUSD': 13914671},
    {'date': 1688256000, 'totalLiquidityUSD': 14125719},
    {'date': 1688342400, 'totalLiquidityUSD': 14504138},
    {'date': 1688428800, 'totalLiquidityUSD': 14654871},
    {'date': 1688515200, 'totalLiquidityUSD': 14821106},
    {'date': 1688601600, 'totalLiquidityUSD': 15291673},
    {'date': 1688688000, 'totalLiquidityUSD': 16276000},
    {'date': 1688774400, 'totalLiquidityUSD': 17886739},
    {'date': 1688860800, 'totalLiquidityUSD': 18371319},
    {'date': 1688947200, 'totalLiquidityUSD': 18023830},
    {'date': 1689033600, 'totalLiquidityUSD': 18342852},
    {'date': 1689120000, 'totalLiquidityUSD': 20502300},
    {'date': 1689206400, 'totalLiquidityUSD': 20148705},
    {'date': 1689292800, 'totalLiquidityUSD': 27623649},
    {'date': 1689379200, 'totalLiquidityUSD': 26047206},
    {'date': 1689465600, 'totalLiquidityUSD': 26914201},
    {'date': 1689552000, 'totalLiquidityUSD': 27601815},
    {'date': 1689638400, 'totalLiquidityUSD': 26915560},
    {'date': 1689724800, 'totalLiquidityUSD': 26574090},
    {'date': 1689811200, 'totalLiquidityUSD': 27533864},
    {'date': 1689897600, 'totalLiquidityUSD': 26553215},
    {'date': 1689984000, 'totalLiquidityUSD': 27270958},
    {'date': 1690070400, 'totalLiquidityUSD': 25706826},
    {'date': 1690156800, 'totalLiquidityUSD': 26240936},
    {'date': 1690243200, 'totalLiquidityUSD': 24642102},
    {'date': 1690329600, 'totalLiquidityUSD': 27615874},
    {'date': 1690416000, 'totalLiquidityUSD': 32385435},
    {'date': 1690502400, 'totalLiquidityUSD': 34181530},
    {'date': 1690588800, 'totalLiquidityUSD': 33963513},
    {'date': 1690675200, 'totalLiquidityUSD': 34401904},
    {'date': 1690761600, 'totalLiquidityUSD': 33806814},
    {'date': 1690848000, 'totalLiquidityUSD': 33152302},
    {'date': 1690934400, 'totalLiquidityUSD': 34169959},
    {'date': 1691020800, 'totalLiquidityUSD': 33264505},
    {'date': 1691107200, 'totalLiquidityUSD': 33043590},
    {'date': 1691193600, 'totalLiquidityUSD': 34158414},
    {'date': 1691280000, 'totalLiquidityUSD': 34471120},
    {'date': 1691366400, 'totalLiquidityUSD': 35277066},
    {'date': 1691452800, 'totalLiquidityUSD': 35653534},
    {'date': 1691539200, 'totalLiquidityUSD': 33959503},
    {'date': 1691625600, 'totalLiquidityUSD': 34326016},
    {'date': 1691712000, 'totalLiquidityUSD': 34814173},
    {'date': 1691798400, 'totalLiquidityUSD': 34594503},
    {'date': 1691884800, 'totalLiquidityUSD': 35430201},
    {'date': 1691971200, 'totalLiquidityUSD': 35122068},
    {'date': 1692057600, 'totalLiquidityUSD': 36758906},
    {'date': 1692144000, 'totalLiquidityUSD': 35052836},
    {'date': 1692230400, 'totalLiquidityUSD': 33867397},
    {'date': 1692316800, 'totalLiquidityUSD': 32495414},
    {'date': 1692403200, 'totalLiquidityUSD': 31917303},
    {'date': 1692489600, 'totalLiquidityUSD': 32597957},
    {'date': 1692576000, 'totalLiquidityUSD': 32081954},
    {'date': 1692662400, 'totalLiquidityUSD': 31462677},
    {'date': 1692748800, 'totalLiquidityUSD': 30836231},
    {'date': 1692835200, 'totalLiquidityUSD': 32698340},
    {'date': 1692921600, 'totalLiquidityUSD': 31455204},
    {'date': 1693008000, 'totalLiquidityUSD': 30913920},
    {'date': 1693094400, 'totalLiquidityUSD': 30904856},
    {'date': 1693180800, 'totalLiquidityUSD': 32246128},
    {'date': 1693267200, 'totalLiquidityUSD': 31596215},
    {'date': 1693353600, 'totalLiquidityUSD': 34293970},
    {'date': 1693440000, 'totalLiquidityUSD': 32363289},
    {'date': 1693526400, 'totalLiquidityUSD': 31277173},
    {'date': 1693612800, 'totalLiquidityUSD': 30639848},
    {'date': 1693699200, 'totalLiquidityUSD': 30859908},
    {'date': 1693785600, 'totalLiquidityUSD': 31088256},
    {'date': 1693872000, 'totalLiquidityUSD': 31030551},
    {'date': 1693958400, 'totalLiquidityUSD': 32504733},
    {'date': 1694044800, 'totalLiquidityUSD': 33067518},
    {'date': 1694131200, 'totalLiquidityUSD': 34406741},
    {'date': 1694217600, 'totalLiquidityUSD': 33942126},
    {'date': 1694304000, 'totalLiquidityUSD': 33690964},
    {'date': 1694390400, 'totalLiquidityUSD': 31690272},
    {'date': 1694476800, 'totalLiquidityUSD': 32238678},
    {'date': 1694563200, 'totalLiquidityUSD': 33065827},
    {'date': 1694649600, 'totalLiquidityUSD': 34241136},
    {'date': 1694736000, 'totalLiquidityUSD': 34910430},
    {'date': 1694822400, 'totalLiquidityUSD': 36446877},
    {'date': 1694908800, 'totalLiquidityUSD': 36097164},
    {'date': 1694995200, 'totalLiquidityUSD': 35777340},
    {'date': 1695081600, 'totalLiquidityUSD': 38280230},
    {'date': 1695168000, 'totalLiquidityUSD': 39458674},
    {'date': 1695254400, 'totalLiquidityUSD': 44567160},
    {'date': 1695340800, 'totalLiquidityUSD': 43785500},
    {'date': 1695427200, 'totalLiquidityUSD': 44453847},
    {'date': 1695513600, 'totalLiquidityUSD': 44735471},
    {'date': 1695600000, 'totalLiquidityUSD': 44349309},
    {'date': 1695686400, 'totalLiquidityUSD': 44958117},
    {'date': 1695772800, 'totalLiquidityUSD': 44539935},
    {'date': 1695859200, 'totalLiquidityUSD': 45620661},
    {'date': 1695945600, 'totalLiquidityUSD': 47419366},
    {'date': 1696032000, 'totalLiquidityUSD': 48789319},
    {'date': 1696118400, 'totalLiquidityUSD': 51236117},
    {'date': 1696204800, 'totalLiquidityUSD': 57559978},
    {'date': 1696291200, 'totalLiquidityUSD': 56307584},
    {'date': 1696377600, 'totalLiquidityUSD': 56107644},
    {'date': 1696464000, 'totalLiquidityUSD': 55579022},
    {'date': 1696550400, 'totalLiquidityUSD': 55239424},
    {'date': 1696636800, 'totalLiquidityUSD': 56989196},
    {'date': 1696723200, 'totalLiquidityUSD': 56632923},
    {'date': 1696809600, 'totalLiquidityUSD': 56492419},
    {'date': 1696896000, 'totalLiquidityUSD': 53917104},
    {'date': 1696982400, 'totalLiquidityUSD': 55470431},
    {'date': 1697068800, 'totalLiquidityUSD': 55824615},
    {'date': 1697155200, 'totalLiquidityUSD': 55083886},
    {'date': 1697241600, 'totalLiquidityUSD': 56452003},
    {'date': 1697328000, 'totalLiquidityUSD': 57713586},
    {'date': 1697414400, 'totalLiquidityUSD': 58406721},
    {'date': 1697500800, 'totalLiquidityUSD': 64385214},
    {'date': 1697587200, 'totalLiquidityUSD': 65921448},
    {'date': 1697673600, 'totalLiquidityUSD': 64845209},

In [6]:
# Extract the TVL data 

# *The raw tvl data has a bunch of headers and fluff so we have to start lower down;)

tvl_data = response['chainTvls']['Solana']['tvl']

# Create an empty list to store the processed data:

processed_data = []

for entry in tvl_data:
    row = {
        'date': datetime.fromtimestamp(entry['date']).strftime('%Y-%m-%d')
        , 'totalLiquidityUSD': entry['totalLiquidityUSD']
    }
                                        
    # Handle token breakdowns if present:
    if 'tokens' in entry:
        for token, amount in entry['tokens'].items():
            row[f'token_{token}'] = amount
            
    processed_data.append(row)
    
# Create the dataframe (for the token whose TVL/ data will be overlaid on the Solana baseline):
df_token = pd.DataFrame(processed_data)

# Set 'date' as the index & sort (this is optional, but DateTimeIndex is helpful for time-series analysis):
df_token.set_index('date', inplace=True)
df_token = df_token.sort_index()

# The usual dataframe sneak-a-peak operations to see shape, info/dtypes/nulls & first few rows:
print(df_token.shape)
print(df_token.info())

df_token.head(3)

(1163, 1)
<class 'pandas.core.frame.DataFrame'>
Index: 1163 entries, 2022-11-23 to 2026-01-28
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   totalLiquidityUSD  1163 non-null   int64
dtypes: int64(1)
memory usage: 18.2+ KB
None

            totalLiquidityUSD
date
2022-11-23            4515393
2022-11-24            4467877
2022-11-25            4472156

In [9]:
# Create a column to show day-over-day percent change:

def add_percent_change(df, tvl_column):
    
    # Sort the dataframe by date:
    df = df.sort_index()
    
    # Calculate % change:
    df['TVL_percent_change'] = df[tvl_column].pct_change() * 100
    
    # Format the % change to two decimal places (avoids unnecessary clutter):
    df['TVL_percent_change'] = df['TVL_percent_change']\
            .apply(lambda x: f"{x:.2f}" if pd.notnull(x) else None)
    
    return df

In [10]:
df_token = add_percent_change(df_token, 'totalLiquidityUSD')
df_token.head(3)

            totalLiquidityUSD TVL_percent_change
date
2022-11-23            4515393               None
2022-11-24            4467877              -1.05
2022-11-25            4472156               0.10

In [11]:
df_token.columns

Index(['totalLiquidityUSD', 'TVL_percent_change'], dtype='object')

In [12]:
# Built a line plot w/ plotly express for the token

fig_token = px.line(
    df_token
    , x=df_token.index
    , y='totalLiquidityUSD'
    , width=1200, height=900
    , title='Total Value Locked (TVL) in USD, over time for Jito Liquid Staking' 
    , labels={
        'totalLiquidityUSD': 'Total Liquidity (USD)'
        , 'date': 'Date'
        , 'TVL_percent_change': '% Change'
    }
    , template='plotly'
    , markers=True
    , color_discrete_sequence=['red']
    , hover_data={'TVL_percent_change': True}
)

# Improve the layout
fig_token.update_layout(
    xaxis_title='Date'
    , yaxis_title='Total Value Locked [TVL] (USD)'
    , hovermode='x unified'
    , yaxis_tickformat='$,.0f'
)

fig_token.update_xaxes(
    rangeslider_visible=True
)

fig_token.update_traces(
    line=dict(
        width=3)
)

fig_token.show()